### ISSUE TITLE
Generalize how remote objects and link types may be stored

### ISSUE THREAD

**Issue by Menrath** [Automattic/wordpress-activitypub#1914]
Follow up of https://github.com/Automattic/wordpress-activitypub/issues/1297

Currently most remote objects are only stored as comments. This is fine, as comments are Notes only and there is no other remote comment than replies to original posts.

The Friends plugin (@akirk) stores incoming objects too, probably in it's own way. The Event Bridge does too, again a different implementation.

I suggest  to start with introduce a unified way how to mark `posts` of all post types as "remote with ActivityPub source", e.g. via a unified meta-key that references an actor (`ap_actor`).

Maybe think of allowing relationships between a comment and a `post`, replies are mostly Notes, but do they have to be?

**Comment by Menrath** [comment]
I mention this yesterday in a discussion with @akirk. Maybe a custom post status, e.g. `activitypub_remote` along with a post_meta `_ap_actor`, could be proposed and advertised.

**Comment by obenland** [comment]
@Menrath [Is this fixed with the new `ap_post` post type](https://github.com/Automattic/wordpress-activitypub/blob/trunk/includes/handler/class-create.php#L44)?

**Comment by Menrath** [comment]
@obenland I will review it next week!

**Comment by Menrath** [comment]
@obenland 

**TL/DR:** I guess to answer that question I have to really work with the code hands on and migrate features of the Event Bridge to it, not just read and review!

I guess it is not solved completely, but the recent changes around the inbox/attachments/`ap_post` etc are huge improvements and are laying a good foundation for a lot of cool applications to come!

I looked into the code, but I think it's easier to give you two example scenarios, than to point out each line of code where a filter/change etc. could be useful at this moment.

1. Event-Bridge like aggregation of events. Following other ActivityPub profiles in order to list their events too. I guess I could hook into the follow table to insert an boolean trigger to activate the behaviour for each followed Actor (not just follow, but also use that Actor as an event source and list their events). When receiving remote `ap_actor`s I need to create an post with the corresponding event post type. 

It is complex. I guess I could currently hook and disable the creation of an `ap_post` and still create an event post. The attachment class and the `ap_post` class are quite tensely linked, I guess I would have a hard time using it on another post_type than `ap_post`. In order to give better feedback, I need to really dive into migrating the existing features and make use of your modernisations and really go to the point where there are missing parts, it's hard to tell from an observer point of view. I can start coding so next week. 

2. A more simple scenario: You build an ActivityPub reader within WordPress. There you show a timeline which is basically `ap_post`s. But when receiving an object type that is a more special object type the `activity_to_post` is maybe not enough. Maybe you want to control this transformation a bit more nuanced.

The transformation from ActivityPub-object to WP_Post (`ap_post`) is quite static. Maybe a Factory could be useful. I did one in the Event Bridge an just called that process transmogrify not to mix up the two directions.

**Comment by Menrath** [comment]
@pfefferle What do you think about adding a post-type capability and registering the relevant comment meta (see https://github.com/Automattic/wordpress-activitypub/blob/424eb98787f8ef0b45f379e13a3f8ed0ab12bd33/includes/class-post-types.php#L351) for all post types that support "ap_remote_cached" (don't mind my naming here)?

By default only the ap_post gets that capability. But other plugins could easily add it to their own post type.
